name: Deploy Express.js App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -y -qq sshpass

    - name: Deploy to VPS
      run: |
        # Pastikan password diteruskan dengan benar menggunakan sshpass
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p /var/www/storyku-server.myzaki.store"
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./ $SSH_USER@$SSH_HOST:/var/www/storyku-server.myzaki.store/

        # Masuk ke folder 'server' untuk backend, install dependencies dan jalankan aplikasi dengan npm run dev
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /var/www/storyku-server.myzaki.store/server && npm install && npm run dev"