image: node:latest

stages:
  - build
  - deploy


build:
  stage: build
  script:
    - npm install

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p /var/www/storyku-server.myzaki.store"
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r ./* $SSH_USER@$SSH_HOST:/var/www/storyku-server.myzaki.store/
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /var/www/storyku-server.myzaki.store && npm install -g pm2 && pm2 restart storyku-zaki || pm2 start app.js --name storyku-zaki"
  only:
    - main
